# wallust v3.1
#
# If comming from v2: https://explosion-mental.codeberg.page/wallust/v3.html#wallusttoml
#
# THIS IS A SAMPLE AND EASY TO COMPREHEND CONFIG, for more info:
#    `man wallust.5` or check the wiki in the repo
#
# You can copy this file to ~/.config/wallust/wallust.toml

# -- global space -- # values below can be overwritten by command line flags

# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "resized"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lab"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"

# Ensures a "readable contrast" (OPTIONAL, disabled by default)
# Should only be enabled when you notice an unreadable contrast frequently happening
# with your images. The reference color for the contrast is the background color.
#check_contrast = true

# Color saturation, between [1% and 100%] (OPTIONAL, disabled by default)
# usually something higher than 50 increases the saturation and below
# decreases it (on a scheme with strong and vivid colors)
#saturation = 35

# Alpha value for templating, by default 100 (no other use whatsoever)
#alpha = 100

[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A relative path that points to a file where wallust.toml is located, usually at `~/.config/wallust/`.
# target: Absolute path in which to place a file with generated templated values.
# If one is a directory, the other one NEEDS to also be one, one line example below
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/waybarColors.css'
